apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-green
  name: webapp-green
spec:
  containers:
  - command:
    - color=green
    image: kodekloud/webapp-greeen
    name: kodekloud/webapp-green