# 
# how to change data to encoded data
# `echo -n "mysql" | base64`  # bxlzcWw=
# `echo -n "root" | base64`   # cm9vdA==
# `echo -n "paswrd" | base64` # cGFzd3Jk
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
data:
  DB_Host: bxlzcWw=       # `echo -n "mysql" | base64`
  DB_User: cm9vdA==       # `echo -n "root" | base64`
  DB_Password: cGFzd3Jk   # `echo -n "paswrd" | base64`

--- 
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: webapp-pod
  name: webapp-pod
spec:
  containers:
  - image: kodekloud/simple-webapp-mysql
    name: webapp-pod
    envFrom:
      - secretRef:
          name: app-secret # secret name
---
# for detail secret information run the following
# `kubectl get secret app-secret -o yaml``

