apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: ["sleep2.0"]  # Entrypoint in dockerfile
    args: ["10"]  # CMD field in dockerfile
---
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod-2
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: ["sleep", "10" ]
--- 
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-sleeper-pod-3
spec:
  containers:
  - name: ubuntu-sleeper
    image: ubuntu-sleeper
    command: 
    - "sleep"
    - "10"
