apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: monitoring-daemon
  #namespace: monitoring
spec:
  selector:
    matchLabels:
      app: monitoring-agent
  template:
    metadata:
      labels:
        app: monitoring-agent
    spec:
      containers:
        - name: agent-container
          image: amazonlinux:latest  # Replace with the desired container image
 