apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:  # Labels & Selectors
    app: App1      
    function: Front-end
spec:
  containers:
  - name: nginx-container
    image: nginx:1.14.2
    ports:
    - containerPort: 80
