apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: simple-webapp
  labels:  # labels of the Replicaset
    app: App1
    function: Front-end
  annotations:
    buildversion: 1.34
spec:
  replicas: 3
  selector:
    matchLabels:
      app: App1
  template: 
    metadata:
      labels:  # Labels here are configured on the pods.
        app: App1   ## selector should match template / metadata
        function: Front-end
    spec:
      containers:
      - name: simple-webapp
        image: simple-webapp