apiVersion: v1
kind: Service
metadata:
  name: sample-phyton-app-service
spec:
  type: NodePort
  selector:
    # inside deployment from template section get app name
    app.kubernetes.io/name: sample-python-app
  ports:
    - port: 80
      # By default and for convenience, the `targetPort` is set to
      # the same value as the `port` field.
      targetPort: 8000   # taget port is where my application is running.
      # Optional field
      # By default and for convenience, the Kubernetes control plane
      # will allocate a port from a range (default: 30000-32767)
      nodePort: 30007