# Task 1: make a zip archive opt.zip of /opt directory 
# Task 2: save it under /root directory on web1 node itself.

- name: zip archive
  hosts: web1
  tasks:
   - name: create archive opt.zip
     archive:
       path: /opt
       dest: /root/opt.zip
       format: zip                    
# extract local.zip archive
- name: extract local.zip archive
  hosts: web1
  tasks:
   - name: unzip local.zip to /tmp 
     unarchive:
       src: local.zip
       dest: /tmp

# Task 1: extract it under /srv directory by developing a playbook ~/playbooks/data.yml 
# Task 2: make sure data.tar.gz archive is removed after that.
- name: archive data.tar.gz
  hosts: web1
  tasks:
   - name: extract
     unarchive:
       src: /root/data.tar.gz
       dest: /srv
       remote_src: yes  # must be there
   - name: remove file
     file:
       state: absent
       path: /root/data.tar.gz

# We have three files on web1 node /root/file1.txt, /usr/local/share/file2.txt and /var/log/lastlog. 
# Create a bz2 archive of all these files and save it under /root directory, 
# name the archive as files.tar.bz2. 

- name: Compress multiple files
  hosts: web1
  tasks:
  - archive:
     path:
      - /root/file1.txt
      - /usr/local/share/file2.txt
      - /var/log/lastlog
     dest: /root/files.tar.bz2
     format: bz2

# We want to setup nginx on web1 node with some sample html code. Create a playbook ~/playbooks/nginx.yml to do so. Below are the details about the task:
# a. Install nginx package and start/enable its service.
# b. Extract /root/nginx.zip archive under /usr/share/nginx/html directory.
# c. Inside /usr/share/nginx/html/index.html replace line This is sample html code with line This is KodeKloud Ansible lab. 

- name: Install and configure nginx on web1
  hosts: web1
  tasks:
  - name: Install nginx
    yum: name=nginx state=installed
  - name: Start nginx
    service: name=nginx state=started enabled=yes

  - name: Extract nginx.zip
    unarchive: src=/root/nginx.zip dest=/usr/share/nginx/html remote_src=yes

  - name: Replace line in index.html
    replace:
     path: /usr/share/nginx/html/index.html
     regexp: This is sample html code
     replace: This is KodeKloud Ansible lab
