apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
spec:
  type: NodePort
  selector:
    app: nginx
    type: front-end
  ports: 
    - targetPort: 80
      port: 80
      nodePOrt: 30008
---
apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: ClusterIP
  selector:
    app: nginx
    type: back-end
  ports: 
    - targetPort: 80
      port: 80
---
apiVersion: v1
kind: Service
metadata:
  name: back-end
spec:
  type: LoadBalancer
  ports: 
    - targetPort: 80
      port: 80