apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        component: api
    spec:
      containers:
        - name: nginx
          image: nginx

#``` kustomization.yaml
# patches:
#   - label-patch.yaml
#```   


# "label-patch.yaml       ```
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: api-deployment
# spec:
#   template:
#     metadata:
#       labels:
#         component: web 