# Job (task) creates one or more Pods and will continue to retry execution of the Pods until a specified number of them successfully terminate. 
# As pods successfully complete, the Job tracks the successful completions. When a specified number of successful completions is reached, 
# the task (ie, Job) is complete. Deleting a Job will clean up the Pods it created. 
# Suspending a Job will delete its active Pods until the Job is resumed again.

apiVersion: batch/v1
kind: Job
metadata:
  name: countdown-xfusion
spec:
  template:
    metadata:
      name: countdown-xfusion
    spec:
      containers:
        - args:
          - sleep
          - "5"
          image: fedora:latest
          name: container-countdown-xfusion
      restartPolicy: Never