apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: flighttickets.flights.com
spec:
  scope: Namespaced
  group: flights.com
  names:
    kind: FlightTicket
    plural: flighttickets
    singular: flightticket
    shortNames:
    - ft
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                from:
                  type: string
                to:
                  type: string
                number:
                  type: integer
                  minimum: 1
                  maximum: 10

# kubectl apply -f crd-definition.yml
# customresourcedefinition.apiextensions.k8s.io/flighttickets.flights.com created
# after creating the above CRD, we can create the custom resource object
---
apiVersion: flights.com/v1
kind: FlightTicket
metadata:
  name: my-flight-ticket
spec:
  from: "SFO"
  to: "JFK"
  number: 1
# kubectl apply -f flightticket.yml
# flightticket.flights.com/my-flight-ticket created
# kubectl get flightticket
# create a custom controller to watch the custom resource object

