
apiVersion: v1
kind: Config

clusters:
- name: my-kube-playground
  cluster:
    server: https://my-cluster-api-server:6443  # Kubernetes API server endpoint
    certificate-authority: /path/to/ca.crt  # CA certificate to verify the API server

contexts:  # combind cluster and user
- name: my-kube-admin@my-kube-playground
  context:
    cluster: my-kube-playground
    user: my-admin-user
    namespace: default  # Default namespace to use

current-context: my-context  # The context `kubectl` will use by default

users:
- name: my-admin-user
  user:
    client-certificate: /path/to/admin.crt  # Client certificate for authentication
    client-key: /path/to/admin.key  # Private key for the client certificate

# Optional: Define multiple users, clusters, and contexts if needed
