apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  accessModes:
    - ReadWriteOnce  # ReadOnlyMany |  ReadWriteMany
  capacity:
    storage: 1Gi
  hostPath:   #option 1  (hostPath volume type is for local work)
      path: /data
      type: Directory
  awsElasticBlockStore:   #(In production we use a volume type like AWS EBS)
      volumeID: <volume-id>
      fsType: ext4