apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: google-storage
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard [ pd-standard | pd-ssd ]
  replication-type: none
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myclaim   # this goes to pod-definition (clainName)
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: google-storage  # this is from storage class definition
  resources:
    requests:
      storage: 500Mi
--- 
apiVersion: v1
kind: Pod
metadata:
  name: random-number-generator
spec:
  containers:
  - name: alpine
    image: alpine
    command: ["/bin/sh", "-c"]
    args: ["shuf -i 0-100 -n 1 >> /opt/number.out;"]
    volumeMounts:
    - mountPath: /opt
      name: data-volume
  volumes:
  - name: data-volume
    persistentVolumeClaim:
      claimName: myclaim  # this is metadata name PVC definition

## The Storage Class called local-storage makes use of VolumeBindingMode set to WaitForFirstConsumer. 
## This will delay the binding and provisioning of a PersistentVolume until a Pod using the PersistentVolumeClaim is created.